let Tapsell = require("react-native").NativeModules.TapsellReactNative;

module.exports = {
	ON_AD_AVAILABLE_EVENT: Tapsell.ON_AD_AVAILABLE_EVENT,
	ON_ERROR_EVENT: Tapsell.ON_ERROR_EVENT,
	ON_NO_AD_AVAILABLE_EVENT: Tapsell.ON_NO_AD_AVAILABLE_EVENT,
	ON_NO_NETWORK_EVENT: Tapsell.ON_NO_NETWORK_EVENT,
	ON_EXPIRING_EVENT: Tapsell.ON_EXPIRING_EVENT,
	ON_OPENED_EVENT: Tapsell.ON_OPENED_EVENT,
	ON_CLOSED_EVENT: Tapsell.ON_CLOSED_EVENT,
	ROTATION_LOCKED_PORTRAIT: Tapsell.ROTATION_LOCKED_PORTRAIT,
	ROTATION_LOCKED_LANDSCAPE: Tapsell.ROTATION_LOCKED_LANDSCAPE,
	ROTATION_UNLOCKED: Tapsell.ROTATION_UNLOCKED,
	ROTATION_LOCKED_REVERSED_PORTRAIT:
		Tapsell.ROTATION_LOCKED_REVERSED_PORTRAIT,
	ROTATION_LOCKED_REVERSED_LANDSCAPE:
		Tapsell.ROTATION_LOCKED_REVERSED_LANDSCAPE,
	PERMISSION_HANDLER_DISABLED: Tapsell.PERMISSION_HANDLER_DISABLED,
	PERMISSION_HANDLER_AUTO: Tapsell.PERMISSION_HANDLER_AUTO,
	PERMISSION_HANDLER_AUTO_INSIST: Tapsell.PERMISSION_HANDLER_AUTO_INSIST,
	ON_AD_AVAILABLE_NATIVE_EVENT: Tapsell.ON_AD_AVAILABLE_NATIVE_EVENT,
	ON_ERROR_NATIVE_EVENT: Tapsell.ON_ERROR_NATIVE_EVENT,
	ON_NO_AD_AVAILABLE_NATIVE_EVENT: Tapsell.ON_NO_AD_AVAILABLE_NATIVE_EVENT,
	ON_NO_NETWORK_NATIVE_EVENT: Tapsell.ON_NO_NETWORK_NATIVE_EVENT
};
